source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-theme-chirpy", "~> 7.4"
gem "jekyll-remote-theme"
gem "jekyll-paginate"
gem "jekyll-archives"
gem "jekyll-include-cache"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-seo-tag"
